ASSIGNMENT ON CASE 1 & 2 SUB-QUERY



31.) WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT

SQL> SELECT ENAME FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME IN 'ACCOUNTING' ) AN
D SAL > (SELECT SAL FROM EMP WHERE ENAME IN 'SCOTT') ;

ENAME
----------
KING

32.)  WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO

SQL> SELECT * FROM EMP WHERE DEPTNO IN(SELECT DEPTNO FROM DEPT WHERE LOC IN 'CHICAGO' ) AND JOB IN '
MANAGER' ;

     EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     DEPTNO
---------- ---------- --------- ---------- --------- ---------- ---------- ----------
      7698 BLAKE      MANAGER         7839 01-MAY-81       2850                    30

33.) WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING

SQL> SELECT ENAME ,SAL FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME IN 'ACCOUNTING') AND
     SAL > (SELECT SAL FROM EMP WHERE ENAME IN 'KING') ;

no rows selected

34.)  WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN IN THE DEPARTEMENT SALES

SQL> SELECT * FROM EMP WHERE JOB IN 'SALESMAN' AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME IN
 'SALES');

     EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     DEPTNO
---------- ---------- --------- ---------- --------- ---------- ---------- ----------
      7499 ALLEN      SALESMAN        7698 20-FEB-81       1600        300         30
      7521 WARD       SALESMAN        7698 22-FEB-81       1250        500         30
      7654 MARTIN     SALESMAN        7698 28-SEP-81       1250       1400         30
      7844 TURNER     SALESMAN        7698 08-SEP-81       1500          0         30

35.) WAQTD NAME, SAL, JOB, HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING

SQL> SELECT ENAME , SAL, JOB , HIREDATE FROM EMP WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME IN
 'KING' ) AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME IN 'OPERATION' );

no rows selected

36.) DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'.

SQL> SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME LIKE '%S');

     EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     DEPTNO
---------- ---------- --------- ---------- --------- ---------- ---------- ----------
      7499 ALLEN      SALESMAN        7698 20-FEB-81       1600        300         30
      7521 WARD       SALESMAN        7698 22-FEB-81       1250        500         30
      7654 MARTIN     SALESMAN        7698 28-SEP-81       1250       1400         30
      7698 BLAKE      MANAGER         7839 01-MAY-81       2850                    30
      7844 TURNER     SALESMAN        7698 08-SEP-81       1500          0         30
      7900 JAMES      CLERK           7698 03-DEC-81        950                    30

37.) WAQTD DNAME OF THE EMPLOYEES WHOS NAMES HAS CHARACTER 'A' IN IT.

SQL> SELECT DNAME FROM DEPT WHERE DEPTNO IN  (SELECT DEPTNO FROM EMP WHERE ENAME LIKE'%A%');

DNAME
--------------
ACCOUNTING
RESEARCH
SALES

38.) WAQTD DNAME AND LOC OF THE EMPLOYEES WHOS SALARY IS RUPEES 800.

SQL> SELECT DNAME ,LOC FROM DEPT WHERE DEPTNO IN(SELECT DEPTNO FROM EMP WHERE SAL = 800);

DNAME          LOC
-------------- -------------
RESEARCH       DALLAS

39.) WAQTD DNAME OF THE EMPLOYEES WHO EARN COMISSION

SQL> SELECT DNAME FROM DEPT WHERE DEPTNO IN(SELECT DEPTNO FROM EMP WHERE COMM IS NOT NULL);

DNAME
--------------
SALES


40.)  WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 40

SQL> SELECT LOC FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE COMM IS NOT NULL AND DEPTNO 
 = 40);

no rows selected