ASSIGNMENT ON EMP AND MANAGER RELATION.


71.) WAQTD SMITHS REPORTING MANAGERS NAME.

SQL> SELECT ENAME FROM EMP WHERE EMPNO IN
  2  (SELECT MGR FROM EMP WHERE ENAME IN 'SMITH');

ENAME
----------
FORD

72.) WAQTD ADAMS MANAGERS MANAGER NAME

SQL> SELECT ENAME FROM EMP WHERE EMPNO IN
  2  (SELECT MGR FROM EMP WHERE EMPNO IN
  3  (SELECT MGR FROM EMP WHERE ENAME IN 'ADAMS') )


ENAME
----------
JONES

73.) WAQTD DNAME OF JONES MANAGER

SQL> SELECT DNAME FROM DEPT WHERE
  2  DEPTNO IN (SELECT DEPTNO FROM EMP WHERE
  3  EMPNO IN ( SELECT MGR FROM EMP WHERE
  4  ENAME IN 'JONES') );

DNAME
--------------
ACCOUNTING


74.) WAQTD MILLER'S MANAGER'S SALARY

SQL> SELECT SAL FROM EMP WHERE EMPNO IN
  2  (SELECT MGR FROM EMP WHERE ENAME IN 'MILLER');

       SAL
----------
      2450


75.) WAQTD LOC OF SMITHS MANAGERS MANAGER.

SQL> SELECT LOC FROM DEPT WHERE DEPTNO IN (
  2  SELECT DEPTNO FROM EMP WHERE EMPNO IN (
  3  SELECT MGR FROM EMP WHERE EMPNO IN (
  4  SELECT MGR FROM EMP WHERE ENAME IN 'SMITH')));

LOC
-------------
DALLAS

76.) WAQTD NAME OF THE EMPLOYEES REPORTING TO BLAKE

SQL> SELECT ENAME FROM EMP WHERE MGR IN 
  2  (SELECT EMPNO FROM EMP WHERE ENAME IN 'BLAKE');

ENAME
----------
ALLEN
WARD
MARTIN
TURNER
JAMES

77.) WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING

SQL> SELECT COUNT(*) FROM EMP WHERE MGR IN
  2  (SELECT EMPNO FROM EMP WHERE ENAME IN 'KING');

  COUNT(*)
----------
         3

78.) WAQTD DETAILS OF THE EMPLOYEES REPORTING TO JONES

SQL> SELECT * FROM EMP WHERE MGR IN
  2  (SELECT EMPNO FROM EMP WHERE ENAME IN 'JONES');

     EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     DEPTNO
---------- ---------- --------- ---------- --------- ---------- ---------- ----------
      7788 SCOTT      ANALYST         7566 19-APR-87       3000                    20
      7902 FORD       ANALYST         7566 03-DEC-81       3000                    20


79.) WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKES MANAGER

SQL> SELECT ENAME FROM EMP WHERE MGR IN
  2  (SELECT MGR FROM EMP WHERE ENAME IN 'BLAKES');

no rows selected

80.) WAQTD NUMBER OF EMPLOYEES REPORTING TO FORDS MANAGER

SQL> SELECT COUNT(*) FROM EMP WHERE MGR IN
  2  (SELECT MGR FROM EMP WHERE ENAME IN 'FORD');

  COUNT(*)
----------
         2