ASSIGNMENT QUESTIONS ON HAVING CLAUSE


1.) WAQTD DNO AND NUMBER OF EMP WORKING IN EACH DEPT IF THERE ARE ATLEAST 2 CLERKS IN EACH DEPT

SQL> 1  SELECT DEPTNO , COUNT(*) FROM EMP
  2  WHERE JOB IN 'CLERK'
  3  GROUP BY DEPTNO
  4* HAVING COUNT(*) >1

    DEPTNO   COUNT(*)
---------- ----------
        20          2

2.) WAQTD DNO AND TOTAL SAALARYNEEDED TO PAY ALL EMP
    IN EACH DEPT IF THERE ARE ATLEAST 4 EMP IN EACH DEPT

SQL> SELECT DEPTNO , SUM(SAL+NVL(COMM,0)) FROM EMP
  2  GROUP BY DEPTNO
  3  HAVING COUNT(*) > 3;

    DEPTNO SUM(SAL+NVL(COMM,0))
---------- --------------------
        30                11600
        20                10875

3.) WAQTD NUMBER OF EMP EARNING SAL MORE THAN 1200 IN EACH JOB
    AND THE TOTAL SAL NEEDED TO PAY EMP OF EACH JOB MUST EXCEES 3800

SQL> SELECT COUNT(*) ,JOB , SUM(SAL) FROM EMP 
  2  WHERE SAL > 1200
  3  GROUP BY JOB
  4  HAVING SUM(SAL) >3800;

  COUNT(*) JOB         SUM(SAL)
---------- --------- ----------
         4 SALESMAN        5600
         1 PRESIDENT       5000
         3 MANAGER         8275
         2 ANALYST         6000

4.) WAQTD DEPTNO AND NUMBER OF EMP WORKING ONLY IF THERE ARE 2 EMP WORKING IN EACH DEPT AS MANAGER.

SQL> SELECT DEPTNO , COUNT(*) FROM EMP
  2  WHERE JOB IN 'MANAGER'
  3  GROUP BY DEPTNO
  4  HAVING COUNT(*) > 1;

no rows selected

5.) WAQTD JOB AND MAX SAL OF EMP IN EACH JOB IF THE MAX SAL EXCEEDS 2600

SQL> SELECT JOB , MAX(SAL) FROM EMP 
  2  GROUP BY JOB
  3  HAVING MAX(SAL) >2600;

JOB         MAX(SAL)
--------- ----------
PRESIDENT       5000
MANAGER         2975
ANALYST         3000

6.) WAQTD THE SALARIES WHICH ARE REPEATED IN EMP TABLE

SQL> SELECT COUNT(*) , SAL FROM EMP 
  2  GROUP BY SAL
  3  HAVING COUNT(*) >1;

  COUNT(*)        SAL
---------- ----------
         2       1250
         2       3000

7.) WAQTD THE HIREDATE WHICH ARE DUPLICATED IN EMP TABLE

SQL> SELECT COUNT(*) , HIREDATE FROM EMP 
  2  GROUP BY HIREDATE
  3  HAVING COUNT(*) >1;

  COUNT(*) HIREDATE
---------- ---------
         2 03-DEC-81

8.) WAQTD AVG SALARY OF EACH DEPT IF AVG SAL IS LESS THAN 3000

SQL> SELECT DEPTNO , AVG(SAL) FROM EMP
  2  GROUP BY DEPTNO
  3  HAVING AVG(SAL) < 3000;

    DEPTNO   AVG(SAL)
---------- ----------
        30 1566.66667
        20       2175
        10 2916.66667


9.) WAQTD DEPTNO IF THERE ARE ATLEAST 3 EMP IN EACH DEPT WHOS NAME HAS CHAR 'A' OR 'S'.

SQL>1  SELECT DEPTNO, COUNT(*) FROM EMP
  2  WHERE ENAME LIKE '%A%' AND ENAME LIKE '%S%'
  3  GROUP BY DEPTNO
  4* HAVING COUNT(*) >2

no rows selected

10.) WAQTD MIN AND MAX SALARIES OF EACH JOB IF MIN SAL IS MORE THAN 1000 AND MAX SAL IS LESS THAN 5000.

SQL> SELECT JOB , MIN(SAL) , MAX(SAL) FROM EMP
  2  GROUP BY JOB 
  3  HAVING MAX(SAL) <5000 AND MIN(SAL) >1000;

JOB         MIN(SAL)   MAX(SAL)
--------- ---------- ----------
SALESMAN        1250       1600
MANAGER         2450       2975
ANALYST         3000       3000
