ASSIGNMENT ON INNER JOIN :



1.) NAME OF THE EMPLOYEE AND HIS LOCATION OF ALL THE EMPLOYEES.

SQL> SELECT ENAME , LOC
  2  FROM EMP,DEPT
  3  WHERE EMP.DEPTNO IN DEPT.DEPTNO;

ENAME      LOC
---------- -------------
SMITH      DALLAS
ALLEN      CHICAGO
WARD       CHICAGO
JONES      DALLAS
MARTIN     CHICAGO
BLAKE      CHICAGO
CLARK      NEW YORK
SCOTT      DALLAS
KING       NEW YORK
TURNER     CHICAGO
ADAMS      DALLAS
JAMES      CHICAGO
FORD       DALLAS
MILLER     NEW YORK


2.) WAQTD DNAME AND SALARY FOR ALL THE EMPLOYEE WORKING IN ACCOUNTING.

SQL> SELECT DNAME , SAL
  2  FROM EMP ,DEPT
  3  WHERE EMP.DEPTNO IN DEPT.DEPTNO AND 
  4  DNAME IN 'ACCOUNTING' ;

DNAME                 SAL
-------------- ----------
ACCOUNTING           2450
ACCOUNTING           5000
ACCOUNTING           1300

3.) WAQTD DNAME AND ANNUAL SALARY FOR ALL EMPLOYEES WHOS SALARY IS MORE THAN 2340

SQL> SELECT DNAME , SAL*12 ANSAL
  2  FROM EMP ,DEPT
  3  WHERE EMP.DEPTNO IN DEPT.DEPTNO AND 
  4  SAL > 2340 ;

DNAME               ANSAL
-------------- ----------
RESEARCH            35700
SALES               34200
ACCOUNTING          29400
RESEARCH            36000
ACCOUNTING          60000
RESEARCH            36000

4.) WAQTD ENAME AND DNAME FOR EMPLOYEES HAVING CAHARACTER 'A' IN THEIR DNAME

SQL> SELECT ENAME , DNAME 
  2  FROM EMP,DEPT
  3  WHERE EMP.DEPTNO IN DEPT.DEPTNO AND
  4  DNAME LIKE '%A%' ;

ENAME      DNAME
---------- --------------
SMITH      RESEARCH
ALLEN      SALES
WARD       SALES
JONES      RESEARCH
MARTIN     SALES
BLAKE      SALES
CLARK      ACCOUNTING
SCOTT      RESEARCH
KING       ACCOUNTING
TURNER     SALES
ADAMS      RESEARCH
JAMES      SALES
FORD       RESEARCH
MILLER     ACCOUNTING


5.) WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES WORKING AS SALESMAN

SQL> SELECT ENAME ,DNAME 
  2  FROM EMP,DEPT
  3  WHERE EMP.DEPTNO IN DEPT.DEPTNO AND
  4  JOB IN 'SALESMAN' ;

ENAME      DNAME
---------- --------------
ALLEN      SALES
WARD       SALES
MARTIN     SALES
TURNER     SALES


6.) WADTD DNAME AND JOB FOR ALL THE EMPLOYEES WHOS JOB AND DNAME STARTS WITH CHARACTER 'S'

SQL> SELECT DNAME,JOB 
  2  FROM EMP,DEPT
  3  WHERE EMP.DEPTNO IN DEPT.DEPTNO AND
  4  JOB LIKE 'S%' AND DNAME LIKE '%S' ;

DNAME          JOB
-------------- ---------
SALES          SALESMAN
SALES          SALESMAN
SALES          SALESMAN
SALES          SALESMAN



7.) WAQTD DNAME AND MGR NO FOR EMPLOYEES REPORTING TO 7839

SQL> SELECT DISTINCT DNAME , MGR 
  2  FROM EMP,DEPT
  3  WHERE EMPNO IN (SELECT EMPNO FROM EMP 
  4  WHERE MGR IN 7839 ) ;

DNAME                 MGR
-------------- ----------
ACCOUNTING           7839
OPERATIONS           7839
RESEARCH             7839
SALES                7839

8.)  WAQTD DNAME AND HIREDATE FOR EMPLOYEES HIRED AFTER 83 INTO ACCOUNTING OR RESEARCH DEPT

SQL>  SELECT DNAME , HIREDATE
  2  FROM EMP ,DEPT
  3  WHERE EMP.DEPTNO IN DEPT.DEPTNO AND
  4  DNAME IN ('RESEARCH' , 'ACCOUNTING') AND
  5  HIREDATE > '31-DEC-1983'
 

DNAME          HIREDATE
-------------- ---------
RESEARCH       19-APR-87
RESEARCH       23-MAY-87


9.) WAQTD ENAME AND DNAME OF THE EMPLOYEES WHO ARE GETTING COMM IN DEPT 10 OR 30

SQL> SELECT ENAME , DNAME
  2  FROM EMP ,DEPT
  3  WHERE EMP.DEPTNO IN DEPT.DEPTNO AND
  4  DEPT.DEPTNO IN (10,30) AND COMM IS NOT NULL ;

ENAME      DNAME
---------- --------------
ALLEN      SALES
WARD       SALES
MARTIN     SALES
TURNER     SALES


10.) WAQTD DNAME AND EMPNO FOR ALL THE EMPLOYEES WHOs EMPNO ARE (7839,7902) AND ARE WORKING IN LOC NEW YORK.

SQL> SELECT DNAME, EMPNO
  2  FROM EMP, DEPT
  3  WHERE EMP.DEPTNO = DEPT.DEPTNO
  4  AND EMPNO IN (7839, 7902)
  5  AND LOC = 'NEWYORK';

no rows selected