ASSIGNMENT ON MAX & MIN :



41.) WAQTD NAME OF THE EMPLOYEE EARNING MAXIMUM SALARY

SQL>  SELECT ENAME FROM EMP
  2   WHERE SAL = (SELECT MAX(SAL) FROM EMP);

ENAME
----------
KING

42.) WAQTD NAME OF THE EMPLOYEE EARNING MINIMUM SALARY

SQL>  SELECT ENAME FROM EMP
  2   WHERE SAL = (SELECT MIN(SAL) FROM EMP);

ENAME
----------
SMITH

43.) WAQTD NAME AND HIREDATE OF THE EMPLOYEE HIRED BEFORE ALL THE EMPLOYEES (FIRST EMP)

SQL>  SELECT ENAME , HIREDATE FROM EMP
  2  WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM EMP)


ENAME      HIREDATE
---------- ---------
SMITH      17-DEC-80

44.) WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AT THE LAST

SQL> SELECT ENAME , HIREDATE FROM EMP
  2  WHERE HIREDATE = (SELECT MAX(HIREDATE) FROM EMP);

ENAME      HIREDATE
---------- ---------
ADAMS      23-MAY-87

45.) WAQTD NAME, COMM OF THE EMPLOYEE WHO EARNS MIN COMISSION

SQL> SELECT ENAME , COMM FROM EMP 
  2  WHERE COMM IN (SELECT MIN(COMM) FROM EMP);

ENAME            COMM
---------- ----------
TURNER              0

46.) WAQTD NAME, SAL AND COMM OF THE EMPLOYEE EARNING MAXIMUM COMISSION

SQL>  SELECT ENAME , COMM , SAL FROM EMP
  2 WHERE COMM IN (SELECT MAX(COMM) FROM EMP)


ENAME            COMM        SAL
---------- ---------- ----------
MARTIN           1400       1250


47.) WAQTD DETAILS OF THE EMPLOYEE WHO HAS GREATEST EMPNO

SQL>  SELECT * FROM EMP
  2 WHERE EMPNO IN (SELECT MAX(EMPNO) FROM EMP)


     EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     DEPTNO
---------- ---------- --------- ---------- --------- ---------- ---------- ----------
      7934 MILLER     CLERK           7782 23-JAN-82       1300                    10

48.) WAQTD DETAILS OF THE EMPLOYEES HAVING THE LEAST HIREDATE

SQL>  SELECT * FROM EMP
  2 WHERE HIREDATE IN (SELECT MIN(HIREDATE) FROM EMP)


     EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     DEPTNO
---------- ---------- --------- ---------- --------- ---------- ---------- ----------
      7369 SMITH      CLERK           7902 17-DEC-80        800                    20


49.) WAQTD DETAILS OF THE EMPLOYEES EARNING LEAST ANNUAL SALARY

SQL>  SELECT * FROM EMP
  2 WHERE SAL *12 IN (SELECT MIN(SAL*12) FROM EMP)


     EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     DEPTNO
---------- ---------- --------- ---------- --------- ---------- ---------- ----------
      7369 SMITH      CLERK           7902 17-DEC-80        800                    20

50.) WAQTD NAME, ANNUAL SALARY OF THE EMPLOYEES IF THEIR ANNUAL SALARY IS MORE THAN ALL THE SALESMAN

SQL>  SELECT ENAME , SAL*12 AS ANNUALSAL FROM EMP
  2 WHERE SAL *12 >ALL (SELECT SAL*12 FROM EMP WHERE JOB IN 'SALESMAN')


ENAME       ANNUALSAL
---------- ----------
JONES           35700
BLAKE           34200
CLARK           29400
SCOTT           36000
KING            60000
FORD            36000