ASSIGNMENT ON SELF JOIN :



1.) WAQTD NAME OF THE EMPLOYEE AND HIS MANAGERS NAME IF EMPLOYEE IS WORKING AS CLERK

SQL> SELECT E1.ENAME EMPNAME , E2.ENAME MGRNAME
  2  FROM EMP E1 , EMP E2
  3  WHERE E1.EMPNO IN E2.MGR AND 
  4  E1.JOB IN 'CLERK' ;

no rows selected

SQL> SELECT E1.ENAME EMPNAME , E2.ENAME MGRNAME
  2  FROM EMP E1 , EMP E2
  3  WHERE E1.MGR IN E2.EMPNO AND
  4  E1.JOB IN 'CLERK' ;

EMPNAME    MGRNAME
---------- ----------
SMITH      FORD
ADAMS      SCOTT
JAMES      BLAKE
MILLER     CLARK

2.) WAQTD NAME OF THE EMPLOYEE AND MANAGERS DESIGNATION IF MANAGER WORKS IN DEPT 10 OR 20

SQL> SELECT E1.ENAME , E2.JOB 
  2  FROM EMP E1 ,EMP E2
  3  WHERE E1.MGR IN E2.EMPNO AND
  4  E2.DEPTNO IN (10,20);

ENAME      JOB
---------- ---------
SMITH      ANALYST
JONES      PRESIDENT
BLAKE      PRESIDENT
CLARK      PRESIDENT
SCOTT      MANAGER
ADAMS      ANALYST
FORD       MANAGER
MILLER     MANAGER

3.) WAQTD NAME OF THE EMP AND MANAGERS SALARY IF EMPLOYEE AND MANAGER BOTH EARN MORE THAN 2300

SQL> ED
Wrote file afiedt.buf

  1  SELECT E1.ENAME EMPNAME , E2.SAL MGRSAL
  2  FROM EMP E1 , EMP E2
  3  WHERE E1.MGR IN E2.EMPNO AND E1.SAL>2300 AND
  4* E2.SAL > 2300
SQL> /

EMPNAME        MGRSAL
---------- ----------
JONES            5000
BLAKE            5000
CLARK            5000
SCOTT            2975
FORD             2975

4.) WAQTD EMP NAME AND MANAGERS HIREDATE IF EMPLOYEE WAS HIRED BEFORE1982

SQL>  SELECT E1.ENAME AS EMPNAME, E2.HIREDATE AS MGRHIREDATE
  2   FROM EMP E1, EMP E2
  3   WHERE E1.MGR = E2.EMPNO AND E1.HIREDATE < '01-JAN-1982';

EMPNAME    MGRHIREDA
---------- ---------
SMITH      03-DEC-81
ALLEN      01-MAY-81
WARD       01-MAY-81
JONES      17-NOV-81
MARTIN     01-MAY-81
BLAKE      17-NOV-81
CLARK      17-NOV-81
TURNER     01-MAY-81
JAMES      01-MAY-81
FORD       02-APR-81

5.) WAQTD EMP NAME AND MANAGERS COMM IF EMPLOYEE WORKS AS SALESMAN AND MANAGER WORKS IN DEPT 30

SQL> SELECT E1.ENAME EMPNAME , E2.COMM MGRCOMM
  2  FROM EMP E1 , EMP E2
  3  WHERE E1.MGR IN E2.EMPNO AND E1.JOB IN 'SALESMAN' AND
  4  E2.DEPTNO IN 30 ;

EMPNAME       MGRCOMM
---------- ----------
ALLEN
WARD
MARTIN
TURNER

6.) WAQTD EMP NAME AND MANAGER NAME AND THEIR SALARIES IF EMPLOYEE EARNS MORE THAN MANAGER

SQL> SELECT E1.ENAME EMPNAME , E2.ENAME MGRNAME , E1.SAL EMPSAL
  2  FROM EMP E1 , EMP E2
  3  WHERE E1.MGR IN E2.EMPNO AND E1.SAL > E2.SAL;

EMPNAME    MGRNAME        EMPSAL
---------- ---------- ----------
SCOTT      JONES            3000
FORD       JONES            3000

7.) WAQTD EMP NAME AND HIREDATE, MANAGER NAME AND HIREDATE IF MANAGER WAS HIRED BEFORE EMPLOYEE

SQL> SELECT E1.ENAME AS EMPENAME, E1.HIREDATE AS EMPHIREDATE,
  2         E2.ENAME AS MGRENAME, E2.HIREDATE AS MGRHIREDATE
  3  FROM EMP E1, EMP E2
  4  WHERE E1.MGR = E2.EMPNO AND E1.SAL > E2.SAL;

EMPENAME   EMPHIREDA MGRENAME   MGRHIREDA
---------- --------- ---------- ---------
SCOTT      19-APR-87 JONES      02-APR-81
FORD       03-DEC-81 JONES      02-APR-81

8.) WAQTD EMP NAME AND MANAGER NAME IF BOTH ARE WORKING IN SAME JOB

SQL> SELECT E1.ENAME AS EMPLOYEE_NAME, E2.ENAME AS MANAGER_NAME
  2  FROM EMP E1
  3  JOIN EMP E2 ON E1.MGR = E2.EMPNO
  4  WHERE E1.JOB = E2.JOB;

no rows selected

9.) WAQTD EMP NAME AND MANAGER NAME IF MANAGER IS WORKING AS ACTUAL MANAGER

SQL> SELECT E1.ENAME AS EMPLOYEE_NAME, E2.ENAME AS MANAGER_NAME
  2  FROM EMP E1, EMP E2
  3  WHERE E1.MGR = E2.EMPNO AND E2.JOB IN 'MANAGER' ;

EMPLOYEE_N MANAGER_NA
---------- ----------
ALLEN      BLAKE
WARD       BLAKE
MARTIN     BLAKE
SCOTT      JONES
TURNER     BLAKE
JAMES      BLAKE
FORD       JONES
MILLER     CLARK

10.) WAQTD EMP NAME AND MANAGER NAME ALONG WITH THEIR ANNUAL SALARIES IF EMPLOYEE WORKS IN DEPT 10, 20 AND MANAGERS SAL IS GREATER THAN EMPLOYEES SALARY.

SQL> SELECT E1.ENAME AS EMPLOYEE_NAME, E2.ENAME AS MANAGER_NAME,
  2         E1.SAL*12 AS EMPSAL , E2.SAL*12 AS MGRSAL 
  3  FROM EMP E1 ,EMP E2
  4  WHERE E1.MGR = E2.EMPNO AND E1.DEPTNO IN (10,20) AND
  5   E2.SAL > E1.SAL ;

EMPLOYEE_N MANAGER_NA     EMPSAL     MGRSAL
---------- ---------- ---------- ----------
SMITH      FORD             9600      36000
JONES      KING            35700      60000
CLARK      KING            29400      60000
ADAMS      SCOTT           13200      36000
MILLER     CLARK           15600      29400

11.) WAQTD EMPLOYEES NAME AND MANAGERS DESIGNATION FOR ALL THE EMPLOYEES

SQL> SELECT E1.ENAME EMPNAME , E2.JOB MGRJOB
  2   FROM EMP E1 ,EMP E2
  3   WHERE E1.MGR = E2.EMPNO ;

EMPNAME    MGRJOB
---------- ---------
SMITH      ANALYST
ALLEN      MANAGER
WARD       MANAGER
JONES      PRESIDENT
MARTIN     MANAGER
BLAKE      PRESIDENT
CLARK      PRESIDENT
SCOTT      MANAGER
TURNER     MANAGER
ADAMS      ANALYST
JAMES      MANAGER
FORD       MANAGER
MILLER     MANAGER

12.) WAQTD EMPLOYEES NAME AND MANAGERS SALARY FOR ALL THE EMPLOYEES IF MANAGERS SALARY ENDS WITH 50

SQL> SELECT E1.ENAME EMPNAME , E2.SAL MGRSAL
  2   FROM EMP E1 ,EMP E2
  3   WHERE E1.MGR = E2.EMPNO AND
  4  E2.SAL LIKE '%50' ;

EMPNAME        MGRSAL
---------- ----------
ALLEN            2850
WARD             2850
MARTIN           2850
TURNER           2850
JAMES            2850
MILLER           2450