SUB QUERY SELECTION PROGRAM

ASSIGNMENT ON CASE 1


SQL> select * from emp;

     EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     DEPTNO
---------- ---------- --------- ---------- --------- ---------- ---------- ----------
      7369 SMITH      CLERK           7902 17-DEC-80        800                    20
      7499 ALLEN      SALESMAN        7698 20-FEB-81       1600        300         30
      7521 WARD       SALESMAN        7698 22-FEB-81       1250        500         30
      7566 JONES      MANAGER         7839 02-APR-81       2975                    20
      7654 MARTIN     SALESMAN        7698 28-SEP-81       1250       1400         30
      7698 BLAKE      MANAGER         7839 01-MAY-81       2850                    30
      7782 CLARK      MANAGER         7839 09-JUN-81       2450                    10
      7788 SCOTT      ANALYST         7566 19-APR-87       3000                    20
      7839 KING       PRESIDENT            17-NOV-81       5000                    10
      7844 TURNER     SALESMAN        7698 08-SEP-81       1500          0         30
      7876 ADAMS      CLERK           7788 23-MAY-87       1100                    20
      7900 JAMES      CLERK           7698 03-DEC-81        950                    30
      7902 FORD       ANALYST         7566 03-DEC-81       3000                    20
      7934 MILLER     CLERK           7782 23-JAN-82       1300                    10


1.WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS

SQL> SELECT ENAME FROM EMP WHERE SAL > ( SELECT SAL FROM EMP WHERE ENAME IN 'ADAMS' ) ;

ENAME
----------
ALLEN
WARD
JONES
MARTIN
BLAKE
CLARK
SCOTT
KING
TURNER
FORD
MILLER

2.WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING

SQL> SELECT ENAME , SAL FROM EMP WHERE SAL < (SELECT SAL FROM EMP WHERE ENAME IN 'KING' );

ENAME             SAL
---------- ----------
SMITH             800
ALLEN            1600
WARD             1250
JONES            2975
MARTIN           1250
BLAKE            2850
CLARK            2450
SCOTT            3000
TURNER           1500
ADAMS            1100
JAMES             950
FORD             3000
MILLER           1300

3.WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES

 SELECT ENAME , DEPTNO FROM EMP WHERE DEPTNO IN ( SELECT DEPTNO FROM EMP WHERE ENAME IN 'JONES' );

ENAME          DEPTNO
---------- ----------
FORD               20
ADAMS              20
SCOTT              20
JONES              20
SMITH              20

4.WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES

  1* SELECT ENAME , JOB FROM EMP WHERE JOB IN ( SELECT JOB FROM EMP WHERE ENAME IN 'JONES' )
SQL> /

ENAME      JOB
---------- ---------
CLARK      MANAGER
BLAKE      MANAGER
JONES      MANAGER

5.WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THEEMPLOYEES IF THEIR ANNUAL SALARY IS
GREATER THAN WARDS ANNUAL SALARY.

SQL> SELECT EMPNO ,ENAME , SAL*12 FROM EMP WHERE SAL*12 > (SELECT SAL*12 FROM EMP WHERE ENAME IN 'WARD');


     EMPNO ENAME          SAL*12
---------- ---------- ----------
      7499 ALLEN           19200
      7566 JONES           35700
      7698 BLAKE           34200
      7782 CLARK           29400
      7788 SCOTT           36000
      7839 KING            60000
      7844 TURNER          18000
      7902 FORD            36000
      7934 MILLER          15600


6.WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT

SQL> SELECT ENAME , HIREDATE FROM EMP WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE JOB IN 'SCOTT' );


ENAME      HIREDATE
---------- ---------
SMITH      17-DEC-80
ALLEN      20-FEB-81
WARD       22-FEB-81
JONES      02-APR-81
MARTIN     28-SEP-81
BLAKE      01-MAY-81
CLARK      09-JUN-81
TURNER     08-SEP-81


7.WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED AFTER THE PRESIDENT

SQL> SELECT ENAME , HIREDATE FROM EMP WHERE HIREDATE > (SELECT HIREDATE FROM EMP WHERE JOB IN 'PRESIDENT' );


ENAME      HIREDATE
---------- ---------
SMITH      17-DEC-80
ALLEN      20-FEB-81
WARD       22-FEB-81
JONES      02-APR-81
MARTIN     28-SEP-81
BLAKE      01-MAY-81
CLARK      09-JUN-81
TURNER     08-SEP-81


8. WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839

SQL> SELECT ENAME , SAL FROM EMP WHERE SAL < (SELECT SAL FROM EMP WHERE EMPNO IN 7839) ;

ENAME             SAL
---------- ----------
SMITH             800
ALLEN            1600
WARD             1250
JONES            2975
MARTIN           1250
BLAKE            2850
CLARK            2450
SCOTT            3000
TURNER           1500
ADAMS            1100
JAMES             950
FORD             3000
MILLER           1300


9.WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER

SQL> SELECT ENAME , SAL FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME IN 'MILLER' ) AND SAL 
     < (SELECT SAL FROM EMP WHERE ENAME IN 'ALLEN' ) ;

ENAME             SAL
---------- ----------
TURNER           1500

10. WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN
11.WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN.
12.WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH
13.WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER

SQL> SELECT * FROM EMP WHERE JOB IN 'MANAGER' AND DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME IN 'T
     URNER' );


     EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     DEPTNO
---------- ---------- --------- ---------- --------- ---------- ---------- ----------
      7698 BLAKE      MANAGER         7839 01-MAY-81       2850                    30

14.WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING

SQL>  SELECT ENAME , HIREDATE FROM EMP WHERE HIREDATE > '01-JAN-1980' AND HIREDATE < (SELECT HIREDATE  FROM EMP WHERE ENAME = 'KING');


ENAME      HIREDATE
---------- ---------
SMITH      17-DEC-80
ALLEN      20-FEB-81
WARD       22-FEB-81
JONES      02-APR-81
MARTIN     28-SEP-81
BLAKE      01-MAY-81
CLARK      09-JUN-81
TURNER     08-SEP-81


15.WAQTD NAME AND SAL ALONG WITH ANNUAL SAL FOR ALL EMPLOYEES WHOS SAL IS LESS THAN BLAKE AND MORE THAN
3500
16.WAQTD ALL THE DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING
17.WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE

SQL>  SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%' AND DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME I


ENAME
----------
ALLEN


18.WAQTD NAME AND COMM IF EMPLOYEES EARN COMISSION AND WORK IN THE SAME DESIGNATION AS SMITH
19.WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER.
20. WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING.