ASSIGNMENT ON CASE 2:

SQL> SELECT * FROM DEPT;

    DEPTNO DNAME          LOC
---------- -------------- -------------
        10 ACCOUNTING     NEW YORK
        20 RESEARCH       DALLAS
        30 SALES          CHICAGO
        40 OPERATIONS     BOSTON

21.) WAQTD DNAME OF THE EMPLOYEES WHOS NAME IS SMITH

SQL> SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME IN 'SMITH');

DNAME
--------------
RESEARCH

22.) WAQTD DNAME AND LOC OF THE EMPLOYEE WHOS ENAME IS KING

SQL> SELECT DNAME , LOC FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME IN 'KING');

DNAME          LOC
-------------- -------------
ACCOUNTING     NEW YORK

23.) WAQTD LOC OF THE EMP WHOS EMPLOYEE NUMBER IS 7902

SQL> SELECT LOC FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE EMPNO IN 7902);

LOC
-------------
DALLAS

24.) WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOS NAME ENDS WITH 'R'.

SQL>  SELECT * FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%R');

    DEPTNO DNAME          LOC
---------- -------------- -------------
        10 ACCOUNTING     NEW YORK
        30 SALES          CHICAGO


25.) WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT

SQL> SELECT DNAME FROM DEPT WHERE DEPTNO IN(SELECT DEPTNO FROM EMP WHERE JOB IN 'PRESIDENT');

DNAME
--------------
ACCOUNTING

26.) WAQTD NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT

SQL> SELECT ENAME FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME IN 'ACCOUNTING');

ENAME
----------
CLARK
KING
MILLER


27.) WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION CHICAGO

SQL>SELECT ENAME, SAL FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE  LOC IN 'CHICAGO')


ENAME             SAL
---------- ----------
ALLEN            1600
WARD             1250
MARTIN           1250
BLAKE            2850
TURNER           1500
JAMES             950

28.) WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES 

SQL> SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME IN 'SALES');

     EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     DEPTNO
---------- ---------- --------- ---------- --------- ---------- ---------- ----------
      7499 ALLEN      SALESMAN        7698 20-FEB-81       1600        300         30
      7521 WARD       SALESMAN        7698 22-FEB-81       1250        500         30
      7654 MARTIN     SALESMAN        7698 28-SEP-81       1250       1400         30
      7698 BLAKE      MANAGER         7839 01-MAY-81       2850                    30
      7844 TURNER     SALESMAN        7698 08-SEP-81       1500          0         30
      7900 JAMES      CLERK           7698 03-DEC-81        950                    30


29.) WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF EMPLOYEES ARE WORKING IN NEW YORK

SQL> SELECT EMP.* , SAL*12 FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC IN 'NEW YORK'
);

     EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     DEPTNO     SAL*12
---------- ---------- --------- ---------- --------- ---------- ---------- ---------- ----------
      7782 CLARK      MANAGER         7839 09-JUN-81       2450                    10      29400
      7839 KING       PRESIDENT            17-NOV-81       5000                    10      60000
      7934 MILLER     CLERK           7782 23-JAN-82       1300                    10      15600

30.) WAQTD NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT

SQL> SELECT ENAME FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME IN 'OPERATIONS');

no rows selected
